# Generated by Django 5.2.3 on 2025-06-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
